import { describe,it,expect,vi } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
vi.mock('../functions/api/_lib.js',async importOriginal=>({...await importOriginal<any>(),getUser:async(env:any)=>env.user,isCourseTeacher:async()=>true}));
import {onRequestPost as join} from '../functions/api/cohorts.js';
import {onRequestPost as progress} from '../functions/api/progress.js';
import {onRequestPost as enroll,onRequestGet as enrollGet} from '../functions/api/enrollments.js';
import {schemaOnce} from '../functions/api/_schema-once.js';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE progress(user_id TEXT,course_id TEXT,done TEXT,passed_score INTEGER,updated_at INTEGER,PRIMARY KEY(user_id,course_id));');const env:any={user:{id:'u1',role:'learner'},statements:[],DB:{}};env.DB.prepare=(query:string)=>{let args:any[]=[];const stmt={bind(...values:any[]){args=values;return stmt},async run(){env.statements.push(query);const result=sql.prepare(query).run(...args);return{success:true,meta:{changes:Number(result.changes)}}},async first(){return sql.prepare(query).get(...args)||null},async all(){return{results:sql.prepare(query).all(...args)}}};return stmt};env.DB.batch=async statements=>{sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e}};return{env,sql};}
const post=(fn:any,env:any,body:any)=>fn({env,request:new Request('https://example.test/api',{method:'POST',body:JSON.stringify(body)})});
describe('Cloud persistence SQL and retry safety',()=>{
 it('cohort join enrolls atomically, repeated joins do not duplicate rows or events',async()=>{const {env,sql}=setup();env.user.role='admin';await post(join,env,{action:'create',courseId:'course',name:'Study group'});const code=sql.prepare('SELECT invite_code FROM cohorts').get()!.invite_code;env.user.role='learner';await post(join,env,{action:'join',code});await post(join,env,{action:'join',code});expect(sql.prepare('SELECT COUNT(*) n FROM cohort_members').get()!.n).toBe(1);expect(sql.prepare('SELECT COUNT(*) n FROM enrollments').get()!.n).toBe(1);expect(sql.prepare("SELECT COUNT(*) n FROM events WHERE action='cohort_joined'").get()!.n).toBe(1);expect(env.statements.filter(s=>s.includes('CREATE TABLE IF NOT EXISTS cohorts')).length).toBe(1);});
 it('rolls back membership when enrollment write fails',async()=>{const {env,sql}=setup();env.user.role='admin';await post(join,env,{action:'create',courseId:'course',name:'Study'});const code=sql.prepare('SELECT invite_code FROM cohorts').get()!.invite_code;sql.exec("CREATE TRIGGER fail_enroll BEFORE INSERT ON enrollments BEGIN SELECT RAISE(ABORT,'outage'); END");await expect(post(join,env,{action:'join',code})).rejects.toThrow('outage');expect(sql.prepare('SELECT COUNT(*) n FROM cohort_members').get()!.n).toBe(0);});
 it('patches preserve other lessons and grades, no-op retries produce no extra events',async()=>{const {env,sql}=setup();for(const lessonId of [2,1,2])await post(progress,env,{courseId:'course',lessonId,completed:true});sql.exec("UPDATE progress SET passed_score=92");await post(progress,env,{courseId:'course',lessonId:1,completed:false});const row=sql.prepare('SELECT * FROM progress').get()!;expect(JSON.parse(row.done as string)).toEqual([2]);expect(row.passed_score).toBe(92);expect(sql.prepare("SELECT COUNT(*) n FROM events WHERE action='lesson_completed'").get()!.n).toBe(2);});
 it('rejects stale-account queued writes and invalid indices',async()=>{const {env,sql}=setup();expect((await post(progress,env,{courseId:'course',lessonId:1,completed:true,expectedUserId:'other'})).status).toBe(409);expect((await post(progress,env,{courseId:'course',lessonId:-1,completed:true})).status).toBe(400);expect(sql.prepare('SELECT COUNT(*) n FROM progress').get()!.n).toBe(0);});
 it('deduplicates legacy snapshots without touching the grade',async()=>{const {env,sql}=setup();await post(progress,env,{courseId:'course',done:[3,1,3,-1]});const before=sql.prepare('SELECT * FROM progress').get();await post(progress,env,{courseId:'course',done:[1,3],passed_score:100});expect(sql.prepare('SELECT * FROM progress').get()).toEqual(before);});
 it('enrollment retries log once and anonymous reads do not initialize tables',async()=>{const {env,sql}=setup();env.user=null;await enrollGet({env,request:new Request('https://example.test')});expect(env.statements).toEqual([]);env.user={id:'u1',role:'learner'};await post(enroll,env,{kind:'course',targetId:'course'});await post(enroll,env,{kind:'course',targetId:'course'});expect(sql.prepare("SELECT COUNT(*) n FROM events WHERE action='enroll'").get()!.n).toBe(1);});
 it('schema setup coalesces concurrent calls and retries after failures',async()=>{const db={};const init=vi.fn().mockRejectedValueOnce(new Error('outage')).mockResolvedValueOnce(undefined);await expect(Promise.all([schemaOnce(db,'x',init),schemaOnce(db,'x',init)])).rejects.toThrow('outage');expect(init).toHaveBeenCalledTimes(1);await schemaOnce(db,'x',init);await schemaOnce(db,'x',init);expect(init).toHaveBeenCalledTimes(2);});
});
