import { describe,it,expect } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
import { verifyFamilyCredentials } from '../functions/familyCredentials.js';
import { hashPassword,verifyPassword } from '../functions/_password.js';
import { onRequestPost } from '../functions/api/auth/login.js';
const PW='Family-test-long-password';
function database(university=false){
 const db=new DatabaseSync(':memory:');
 db.exec(university?`CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,username TEXT,role TEXT,password_hash TEXT,email_verified INTEGER DEFAULT 0,created_at INTEGER,marketing_optin INTEGER); CREATE TABLE user_mfa(user_id TEXT,enabled_at INTEGER); CREATE TABLE sessions(id TEXT,user_id TEXT,expires_at INTEGER,mfa_ok INTEGER);`:`CREATE TABLE user(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,handle TEXT,email_verified INTEGER); CREATE TABLE account(user_id TEXT,provider_id TEXT,password TEXT);`);
 const binding={prepare(sql:string){const stmt=db.prepare(sql);return {bind(...args:any[]){return {async first(){return stmt.get(...args)||null;},async run(){stmt.run(...args);return {success:true};},async all(){return {results:stmt.all(...args)}}}},async run(){stmt.run();return {success:true}}};}};
 return {db,binding,async seed(email='person@example.com',handle='reader',verified=1){const hash=await hashPassword(PW);if(university)db.prepare('INSERT INTO users(id,email,username,role,password_hash,email_verified) VALUES(?,?,?,?,?,?)').run('u',email,handle,'learner',hash,verified);else{db.prepare('INSERT INTO user VALUES(?,?,?,?,?)').run('u',email,null,handle,verified);db.prepare('INSERT INTO account VALUES(?,?,?)').run('u','credentials',hash);}}};
}
const sites=[['sikhi.io','FAMILY_SIKHI_DB'],['sikhiuni.com','FAMILY_SIKHIUNI_DB'],['punjabiuni.com','FAMILY_PUNJABI_DB']];
describe('family login with real SQLite and password hashing',()=>{
 for(const [source,binding] of sites)for(const [target] of sites)if(source!==target)it(`${source} credentials accepted on ${target}`,async()=>{const origin=database(source==='sikhiuni.com');await origin.seed();const env={FAMILY_SIKHI_DB:database().binding,FAMILY_SIKHIUNI_DB:database(true).binding,FAMILY_PUNJABI_DB:database().binding,[binding]:origin.binding};for(const identifier of ['PERSON@example.com','reader']){const result=await verifyFamilyCredentials(env,target,identifier,PW,verifyPassword);expect(result.ok).toBe(true);if(result.ok)expect(result.identity.email).toBe('person@example.com');}expect((await verifyFamilyCredentials(env,target,'reader','wrong',verifyPassword)).ok).toBe(false);});
 it('requires an email when another username source is unavailable',async()=>{const a=database();await a.seed();expect(await verifyFamilyCredentials({FAMILY_SIKHI_DB:a.binding},'sikhiuni.com','reader',PW,verifyPassword)).toMatchObject({ok:false,error:'family_unavailable'});expect((await verifyFamilyCredentials({FAMILY_SIKHI_DB:a.binding},'sikhiuni.com','person@example.com',PW,verifyPassword)).ok).toBe(true);});
 it('does not trust an unverified source email',async()=>{const a=database();await a.seed('person@example.com','reader',0);expect(await verifyFamilyCredentials({FAMILY_SIKHI_DB:a.binding},'sikhiuni.com','reader',PW,verifyPassword)).toMatchObject({ok:false,error:'verify_email'});});
 it('does not bypass source MFA',async()=>{const a=database(true);await a.seed();a.db.exec("INSERT INTO user_mfa VALUES('u',123)");expect(await verifyFamilyCredentials({FAMILY_SIKHIUNI_DB:a.binding},'sikhi.io','reader',PW,verifyPassword)).toMatchObject({ok:false,error:'source_mfa_required'});});
 it('rejects matching credentials on different username owners',async()=>{const a=database(),c=database();await a.seed('one@example.com');await c.seed('two@example.com');expect(await verifyFamilyCredentials({FAMILY_SIKHI_DB:a.binding,FAMILY_PUNJABI_DB:c.binding},'sikhiuni.com','reader',PW,verifyPassword)).toMatchObject({ok:false,error:'ambiguous_identifier'});});
 it('does not switch a local username to a different identity',async()=>{const a=database();await a.seed();const r=await verifyFamilyCredentials({FAMILY_SIKHI_DB:a.binding},'sikhiuni.com','reader',PW,verifyPassword,'different@example.com');expect(r.ok).toBe(false);});
 it('direct Sikhiuni form provisions once, persists no password and honours local MFA',async()=>{const origin=database(),local=database(true);await origin.seed();const env={DB:local.binding,FAMILY_SIKHI_DB:origin.binding,FAMILY_PUNJABI_DB:database().binding,ADMIN_EMAILS:''};const request=()=>new Request('https://sikhiuni.com/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier:'reader',password:PW})});const a=await onRequestPost({request:request(),env});expect(a.status).toBe(200);expect(a.headers.get('set-cookie')).toContain('HttpOnly');const user=local.db.prepare('SELECT * FROM users').get()!;expect(user.password_hash).toBeNull();expect(user.email).toBe('person@example.com');local.db.prepare('INSERT INTO user_mfa VALUES(?,123)').run(user.id);const b=await onRequestPost({request:request(),env});expect(await b.json()).toMatchObject({ok:true,mfaRequired:true});expect(local.db.prepare('SELECT count(*) AS n FROM users').get()!.n).toBe(1);expect(local.db.prepare('SELECT mfa_ok FROM sessions ORDER BY rowid DESC LIMIT 1').get()!.mfa_ok).toBe(0);});
});
